- name: 'Digital Ocean droplet playbook'
  hosts: 127.0.0.1
  connection: local
  vars:
   droplet_image: "ubuntu-16-04-x64"
   droplet_region: "lon1"
   droplet_size: "512mb"
   droplet_name: "servoid"
  vars_prompt:
   - name: "api_token"
     private: no
     prompt: "Whats your digital ocean api token ?"
   - name: "ssh_key"
     private: no
     prompt: "What ssh key to use ? (if new file we will generate key)"
     default: "id_rsa"
  tasks:
   - name: "Check pip installed"
     command: "pip"

   - name: "Install dopy and dependency modules"
     pip: name="{{item}}" state=present
     with_items:
      - dopy
      - six

   - name: "Check public key exists"
     shell: find ~/.ssh/{{ssh_key}}.pub
     ignore_errors: true
     register: output

   - name: "Create public key"
     shell: ssh-keygen -q -trsa -b4096 -N '' -f ~/.ssh/{{ssh_key}}
     when: output.stderr != ""

   - name: "Extract pub key contents"
     shell: cat ~/.ssh/{{ssh_key}}.pub
     register: public_key

   - name: "Check public key extraction successful"
     fail: msg="Public key extraction failed"
     when: public_key == ""

   - name: "Register ssh key with digital ocean"
     register: key_upload
     digital_ocean: >
      api_token={{api_token}}
      command=ssh
      name={{ssh_key}}_key
      ssh_pub_key={{public_key.stdout}}
      state=present
   - fail: msg="register ssh key with digital ocean failed"
     when: key_upload.ssh_key.id == ''

   - name: "Create Ubuntu 16.04 x64 box"
     register: droplet
     digital_ocean: >
      api_token={{api_token}}
      name={{droplet_name}}
      command=droplet
      image_id={{droplet_image}}
      region_id={{droplet_region}}
      size_id={{droplet_size}}
      ssh_key_ids={{key_upload.ssh_key.id}}
      state=present
      unique_name=true
   - debug: "msg={{droplet.droplet.ip_address}}"

   - name: "Output droplet host to hosts file"
     lineinfile: >
      dest=hosts
      line="\n[server]\n{{droplet.droplet.ip_address}} ansible_python_interpreter=python3"
      state=present
