- name: "Configure server"
  hosts: server
  remote_user: "{{as_user}}"
  become: yes
  become_method: sudo
  vars_files:
   - vars/default.yml
  roles:
   - role: users
     tags:
      - configure
      - users
   - role: firewall
     tags:
      - configure
      - firewall
   - role: package_manager
     tags:
      - configure
      - packages
   - role: security
     tags:
      - configure
      - security

- name: "Daily user setup"
  hosts: server
  tags: programs
  remote_user: "{{user}}"
  vars_files:
   - vars/user.yml
  roles:
   - role: code_checkout
