- name: "Ensure password authentication disabled"
  lineinfile: >
   dest=/etc/ssh/sshd_config
   regexp="^PasswordAuthentication"
   line="PasswordAuthentication no"
   state=present
  notify: "Restart ssh"

- name: "Ensure root ssh access denied"
  lineinfile: >
   dest=/etc/ssh/sshd_config
   regexp="^PermitRootLogin"
   line="PermitRootLogin no"
   state=present
  notify: "Restart ssh"

- name: "Ensure to display banner on failed logins"
  lineinfile: >
   dest=/etc/ssh/sshd_config
   regexp="^.*Banner /etc/issue.net"
   line="Banner /etc/issue.net"
   state=present
  notify: "Restart ssh"

- name: "Ensure generic banner file updated"
  copy: >
   src=banner.txt
   dest=/etc/issue.net
   owner=root
   group=root
   mode=0644
